//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Essence.Translations {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ES_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ES_ES() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Essence.Translations.ES-ES", typeof(ES_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a --La IA mostrará los guiones aquí.
        /// </summary>
        internal static string @__AI_will_output_scripts_here {
            get {
                return ResourceManager.GetString("--AI will output scripts here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Búsqueda profunda de guiones...).
        /// </summary>
        internal static string @__Deep_Searching_Scripts____ {
            get {
                return ResourceManager.GetString(" (Deep Searching Scripts...)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Buscando guiones...).
        /// </summary>
        internal static string @__Searching_Scripts____ {
            get {
                return ResourceManager.GetString(" (Searching Scripts...)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (cargando...).
        /// </summary>
        internal static string _loading____ {
            get {
                return ResourceManager.GetString("(loading...)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a La IA está pensando....
        /// </summary>
        internal static string AI_is_thinking___ {
            get {
                return ResourceManager.GetString("AI is thinking...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aimbot, ESP y más cosas en la próxima actualización.
        /// </summary>
        internal static string Aimbot__ESP_e_mais_coisas_na_próxima_atualização {
            get {
                return ResourceManager.GetString("Aimbot, ESP e mais coisas na próxima atualização", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Todo listo!.
        /// </summary>
        internal static string All_Done_ {
            get {
                return ResourceManager.GetString("All Done!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vaya. Abriendo la ventana de error....
        /// </summary>
        internal static string Bruh__Opening_the_error_window___ {
            get {
                return ResourceManager.GetString("Bruh. Opening the error window...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cambia las propiedades de tu personaje, usa efectos visuales y aimbots.
        /// </summary>
        internal static string Change_your_character_properties__use_visuals_and_aimbots {
            get {
                return ResourceManager.GetString("Change your character properties, use visuals and aimbots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cambia el idioma de tu ejecutor..
        /// </summary>
        internal static string Change_your_executor_language_ {
            get {
                return ResourceManager.GetString("Change your executor language.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificando inicio de sesión.
        /// </summary>
        internal static string Checking_Login {
            get {
                return ResourceManager.GetString("Checking Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comprobando el estado de mantenimiento.
        /// </summary>
        internal static string Checking_Maintence_status {
            get {
                return ResourceManager.GetString("Checking Maintence status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comprobando la versión.
        /// </summary>
        internal static string Checking_Version {
            get {
                return ResourceManager.GetString("Checking Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elige uno de los idiomas disponibles a continuación..
        /// </summary>
        internal static string Choose_one_of_the_available_languages_below_ {
            get {
                return ResourceManager.GetString("Choose one of the available languages below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpiar.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpiar historial.
        /// </summary>
        internal static string Clear_History {
            get {
                return ResourceManager.GetString("Clear History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elección de la comunidad.
        /// </summary>
        internal static string Community_Choice {
            get {
                return ResourceManager.GetString("Community Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmar.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectando.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continuar.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copiado.
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copiar guion.
        /// </summary>
        internal static string Copy_Script {
            get {
                return ResourceManager.GetString("Copy Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario actual: .
        /// </summary>
        internal static string Current_User__ {
            get {
                return ResourceManager.GetString("Current User: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Personaliza tu cuenta.
        /// </summary>
        internal static string Customize_your_account {
            get {
                return ResourceManager.GetString("Customize your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Personaliza tu experiencia Essence.
        /// </summary>
        internal static string Customize_your_Essence_experience {
            get {
                return ResourceManager.GetString("Customize your Essence experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Elimina todos los registros de conversaciones con Mia.
        /// </summary>
        internal static string Delete_all_records_of_conversations_with_Mia {
            get {
                return ResourceManager.GetString("Delete all records of conversations with Mia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escriba el guion aquí..
        /// </summary>
        internal static string Digite_o_script_aqui_ {
            get {
                return ResourceManager.GetString("Digite o script aqui.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RPC de Discord.
        /// </summary>
        internal static string Discord_RPC {
            get {
                return ResourceManager.GetString("Discord RPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error en la descarga. Intente desactivar su software antivirus.
        /// </summary>
        internal static string Download_failed__try_to_disable_your_antivirus_software {
            get {
                return ResourceManager.GetString("Download failed. try to disable your antivirus software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ehh... Lo siento por eso.
        /// </summary>
        internal static string Ehh____Sorry_for_that {
            get {
                return ResourceManager.GetString("Ehh... Sorry for that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Personalización de Essence.
        /// </summary>
        internal static string Essence_Customization {
            get {
                return ResourceManager.GetString("Essence Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro de cambios de las funciones de Essence.
        /// </summary>
        internal static string Essence_Features_Changelog {
            get {
                return ResourceManager.GetString("Essence Features Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correo electrónico.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Habilitar la actividad de Discord para Essence. ¡Yay!.
        /// </summary>
        internal static string Enable_discord_activity_for_Essence__Yay_ {
            get {
                return ResourceManager.GetString("Enable discord activity for Essence. Yay!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coincidencias exactas para.
        /// </summary>
        internal static string Exact_Matches_for {
            get {
                return ResourceManager.GetString("Exact Matches for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ejecutar.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filtrando resultados con IA....
        /// </summary>
        internal static string Filtering_results_with_AI___ {
            get {
                return ResourceManager.GetString("Filtering results with AI...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volar.
        /// </summary>
        internal static string Fly {
            get {
                return ResourceManager.GetString("Fly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sigue las reglas para continuar utilizando nuestros servicios..
        /// </summary>
        internal static string Follow_the_rules_to_continue_using_our_services_ {
            get {
                return ResourceManager.GetString("Follow the rules to continue using our services.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Juego.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID del juego: .
        /// </summary>
        internal static string Game_ID__ {
            get {
                return ResourceManager.GetString("Game ID: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID del juego: Ninguno.
        /// </summary>
        internal static string Game_ID__None {
            get {
                return ResourceManager.GetString("Game ID: None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Juegos que juegas.
        /// </summary>
        internal static string Games_you_play {
            get {
                return ResourceManager.GetString("Games you play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obteniendo nombre del juego....
        /// </summary>
        internal static string Getting_Game_Name___ {
            get {
                return ResourceManager.GetString("Getting Game Name...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obteniendo información de Roblox.
        /// </summary>
        internal static string Getting_Roblox_Info {
            get {
                return ResourceManager.GetString("Getting Roblox Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buenas tardes.
        /// </summary>
        internal static string Good_Afternoon {
            get {
                return ResourceManager.GetString("Good Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buenas noches.
        /// </summary>
        internal static string Good_Evening {
            get {
                return ResourceManager.GetString("Good Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buenos días.
        /// </summary>
        internal static string Good_Morning {
            get {
                return ResourceManager.GetString("Good Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buenas noches.
        /// </summary>
        internal static string Good_Night {
            get {
                return ResourceManager.GetString("Good Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hola.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hola Usuario.
        /// </summary>
        internal static string Hello_User {
            get {
                return ResourceManager.GetString("Hello User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Hola! ¿Necesitas ayuda con guiones? ¡Comencemos!.
        /// </summary>
        internal static string Hi__Need_script_help__Let_s_begin_ {
            get {
                return ResourceManager.GetString("Hi! Need script help? Let\'s begin!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Página Principal.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horas.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Doy mi consentimiento para la recopilación de datos de juegos para ayudar a mejorar el programa..
        /// </summary>
        internal static string I_consent_to_the_collection_of_game_data_to_help_improve_the_program_ {
            get {
                return ResourceManager.GetString("I consent to the collection of game data to help improve the program.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Inserta un enlace de imagen aquí!.
        /// </summary>
        internal static string Insert_an_image_link_here_ {
            get {
                return ResourceManager.GetString("Insert an image link here!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intermedio.
        /// </summary>
        internal static string Intermission {
            get {
                return ResourceManager.GetString("Intermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Únase a nuestro evento musical para obtener una clave gratis!.
        /// </summary>
        internal static string Join_our_music_event_for_free_key_ {
            get {
                return ResourceManager.GetString("Join our music event for free key!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mantener Essence arriba de otras ventanas.
        /// </summary>
        internal static string Keep_Essence_on_top_of_other_windows {
            get {
                return ResourceManager.GetString("Keep Essence on top of other windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resultados menos relevantes.
        /// </summary>
        internal static string Less_relevant_results {
            get {
                return ResourceManager.GetString("Less relevant results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Comencemos!.
        /// </summary>
        internal static string Lets_Start_ {
            get {
                return ResourceManager.GetString("Lets Start!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clave de Linkvertise.
        /// </summary>
        internal static string Linkvertise_key {
            get {
                return ResourceManager.GetString("Linkvertise key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargando conversaciones de la IA.
        /// </summary>
        internal static string Loading_AI_Conversations {
            get {
                return ResourceManager.GetString("Loading AI Conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargando registro de cambios....
        /// </summary>
        internal static string Loading_Changelog___ {
            get {
                return ResourceManager.GetString("Loading Changelog...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargando EULA....
        /// </summary>
        internal static string Loading_EULA___ {
            get {
                return ResourceManager.GetString("Loading EULA...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargando siguiente....
        /// </summary>
        internal static string Loading_Next___ {
            get {
                return ResourceManager.GetString("Loading Next...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargando configuraciones.
        /// </summary>
        internal static string Loading_Settings {
            get {
                return ResourceManager.GetString("Loading Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargando datos del usuario.
        /// </summary>
        internal static string Loading_User_Data {
            get {
                return ResourceManager.GetString("Loading User Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicio de sesión Premium - Permanente.
        /// </summary>
        internal static string Login_Premium___Permanent {
            get {
                return ResourceManager.GetString("Login Premium - Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Haciendo solicitud....
        /// </summary>
        internal static string Making_Request___ {
            get {
                return ResourceManager.GetString("Making Request...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Asistente Mia.
        /// </summary>
        internal static string Mia_Assistent {
            get {
                return ResourceManager.GetString("Mia Assistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Monaco es un editor avanzado. Pero, puede causar problemas de rendimiento en algunos PC.
        /// </summary>
        internal static string Monaco_is_an_advanced_editor__But__it_can_cause_performance_issues_in_some_pc_s {
            get {
                return ResourceManager.GetString("Monaco is an advanced editor. But, it can cause performance issues in some pc\'s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nuevos guiones.
        /// </summary>
        internal static string New_Scripts {
            get {
                return ResourceManager.GetString("New Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Genial!.
        /// </summary>
        internal static string Nice_ {
            get {
                return ResourceManager.GetString("Nice!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Noclip.
        /// </summary>
        internal static string No_Clip {
            get {
                return ResourceManager.GetString("No Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No hay suficientes datos. ¡Juega algunos juegos usando Essence primero!.
        /// </summary>
        internal static string No_enough_data__play_some_games_using_Essence_first_ {
            get {
                return ResourceManager.GetString("No enough data. play some games using Essence first!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No se detectó conexión a Internet.
        /// </summary>
        internal static string No_Internet_Connection_Detected {
            get {
                return ResourceManager.GetString("No Internet Connection Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ahora tu Essence está completamente configurado.
        /// </summary>
        internal static string Now_Your_Essence_are_Fully_Configured {
            get {
                return ResourceManager.GetString("Now Your Essence are Fully Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Nuestra IA está lista para ayudarte!.
        /// </summary>
        internal static string Our_AI_is_ready_to_help_you_ {
            get {
                return ResourceManager.GetString("Our AI is ready to help you!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Nuestros servidores se están actualizando!.
        /// </summary>
        internal static string Our_servers_are_updating_ {
            get {
                return ResourceManager.GetString("Our servers are updating!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID del jugador: .
        /// </summary>
        internal static string Player_ID__ {
            get {
                return ResourceManager.GetString("Player ID: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jugadores en línea: .
        /// </summary>
        internal static string Players_online__ {
            get {
                return ResourceManager.GetString("Players online: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jugadores en línea: Cargando....
        /// </summary>
        internal static string Players_online__Loading___ {
            get {
                return ResourceManager.GetString("Players online: Loading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jugando .
        /// </summary>
        internal static string Playing_ {
            get {
                return ResourceManager.GetString("Playing ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de reproducción vacía..
        /// </summary>
        internal static string Playlist_Empty_ {
            get {
                return ResourceManager.GetString("Playlist Empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, revisa tus configuraciones de red y de tu firewall para restaurar el acceso..
        /// </summary>
        internal static string Please_check_your_network_settings_and_firewall_configuration_to_restore_access_ {
            get {
                return ResourceManager.GetString("Please check your network settings and firewall configuration to restore access.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inicio de sesión Premium (ADM).
        /// </summary>
        internal static string Premium_Login__ADM_ {
            get {
                return ResourceManager.GetString("Premium Login (ADM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preparando la primera ejecución...
        /// </summary>
        internal static string Preparing_First_Run__ {
            get {
                return ResourceManager.GetString("Preparing First Run..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preparando la primera ejecución....
        /// </summary>
        internal static string Preparing_First_Run___ {
            get {
                return ResourceManager.GetString("Preparing First Run...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foto de perfil.
        /// </summary>
        internal static string Profile_Picture {
            get {
                return ResourceManager.GetString("Profile Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configuración de perfil.
        /// </summary>
        internal static string Profile_Settings {
            get {
                return ResourceManager.GetString("Profile Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panel rápido.
        /// </summary>
        internal static string Quick_Panel {
            get {
                return ResourceManager.GetString("Quick Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cosas rápidas que puedes cambiar.
        /// </summary>
        internal static string Quick_things_you_can_change {
            get {
                return ResourceManager.GetString("Quick things you can change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Actualizar.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resultados para.
        /// </summary>
        internal static string Results_for {
            get {
                return ResourceManager.GetString("Results for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guardar conversaciones.
        /// </summary>
        internal static string Save_conversations {
            get {
                return ResourceManager.GetString("Save conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guarda tus pestañas de guiones para recargarlas cuando vuelvas a abrir Essence.
        /// </summary>
        internal static string Save_your_script_tabs_to_re_load_then_when_you_open_Essence_again {
            get {
                return ResourceManager.GetString("Save your script tabs to re-load then when you open Essence again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guiones guardados.
        /// </summary>
        internal static string Saved_Scripts {
            get {
                return ResourceManager.GetString("Saved Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nube de guiones.
        /// </summary>
        internal static string Script_Cloud {
            get {
                return ResourceManager.GetString("Script Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guiones para versiones anteriores de este juego: .
        /// </summary>
        internal static string Scripts_for_past_versions_of_this_game__ {
            get {
                return ResourceManager.GetString("Scripts for past versions of this game: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guiones para este juego: .
        /// </summary>
        internal static string Scripts_for_this_game__ {
            get {
                return ResourceManager.GetString("Scripts for this game: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guiones para este juego: Cargando....
        /// </summary>
        internal static string Scripts_for_this_game__Loading___ {
            get {
                return ResourceManager.GetString("Scripts for this game: Loading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guiones para esta versión del juego: .
        /// </summary>
        internal static string Scripts_for_this_game_version__ {
            get {
                return ResourceManager.GetString("Scripts for this game version: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buscar guiones.
        /// </summary>
        internal static string Search_scripts {
            get {
                return ResourceManager.GetString("Search scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buscando....
        /// </summary>
        internal static string Searching___ {
            get {
                return ResourceManager.GetString("Searching...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saltar de servidor.
        /// </summary>
        internal static string Server_Hop {
            get {
                return ResourceManager.GetString("Server Hop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Establecer poder de salto .
        /// </summary>
        internal static string Set_JumpPower_ {
            get {
                return ResourceManager.GetString("Set JumpPower ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Establecer velocidad de caminar .
        /// </summary>
        internal static string Set_WalkSpeed_ {
            get {
                return ResourceManager.GetString("Set WalkSpeed ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configuración.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Omitir.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Saltando música....
        /// </summary>
        internal static string Skipping_music___ {
            get {
                return ResourceManager.GetString("Skipping music...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lo sentimos, tu idioma no es compatible.
        /// </summary>
        internal static string Sorry__your_language_is_not_supported {
            get {
                return ResourceManager.GetString("Sorry, your language is not supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciando UI....
        /// </summary>
        internal static string Starting_UI___ {
            get {
                return ResourceManager.GetString("Starting UI...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sugerido por: .
        /// </summary>
        internal static string Suggested_by__ {
            get {
                return ResourceManager.GetString("Suggested by: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Juegos sugeridos.
        /// </summary>
        internal static string Suggested_games {
            get {
                return ResourceManager.GetString("Suggested games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sincronizado con tu Discord.
        /// </summary>
        internal static string Synced_with_your_discord {
            get {
                return ResourceManager.GetString("Synced with your discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Habla con el asistente aquí.
        /// </summary>
        internal static string Talk_to_assistent_here {
            get {
                return ResourceManager.GetString("Talk to assistent here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esto está tomando más tiempo de lo esperado....
        /// </summary>
        internal static string This_is_taking_longer_than_expected___ {
            get {
                return ResourceManager.GetString("This is taking longer than expected...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta opción guarda y carga todo tu historial de chat con Mia..
        /// </summary>
        internal static string This_option_saves_and_loads_all_your_chat_history_with_Mia_ {
            get {
                return ResourceManager.GetString("This option saves and loads all your chat history with Mia.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mantener la ventana siempre arriba.
        /// </summary>
        internal static string Top_Most_the_window {
            get {
                return ResourceManager.GetString("Top-Most the window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acción no autorizada detectada. Detente inmediatamente para evitar medidas adicionales..
        /// </summary>
        internal static string Unauthorized_action_detected__Stop_immediately_to_avoid_further_measures_ {
            get {
                return ResourceManager.GetString("Unauthorized action detected. Stop immediately to avoid further measures.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nombre de usuario.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a usuarios escuchando: .
        /// </summary>
        internal static string users_listening__ {
            get {
                return ResourceManager.GetString("users listening: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifica para acceder a nuestros servicios.
        /// </summary>
        internal static string Verify_to_access_our_services {
            get {
                return ResourceManager.GetString("Verify to access our services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifica usando Discord.
        /// </summary>
        internal static string Verify_using_Discord {
            get {
                return ResourceManager.GetString("Verify using Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esperando que el usuario se una a un juego..
        /// </summary>
        internal static string Waiting_for_user_to_join_a_game_ {
            get {
                return ResourceManager.GetString("Waiting for user to join a game.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estamos actualizando nuestros servicios. Por favor, inténtelo más tarde..
        /// </summary>
        internal static string We_re_updating_our_services__Please_try_again_later_ {
            get {
                return ResourceManager.GetString("We\'re updating our services. Please try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Bienvenido, estamos agradecidos de tenerte con nosotros!.
        /// </summary>
        internal static string Welcome__we_are_grateful_to_have_you_with_us_ {
            get {
                return ResourceManager.GetString("Welcome, we are grateful to have you with us!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¡Bienvenido Usuario!.
        /// </summary>
        internal static string Welcome_User_ {
            get {
                return ResourceManager.GetString("Welcome User!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ¿Qué hay de nuevo?.
        /// </summary>
        internal static string What_s_New {
            get {
                return ResourceManager.GetString("What\'s New", resourceCulture);
            }
        }
    }
}
