//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Essence.Translations {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PT_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PT_BR() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Essence.Translations.PT-BR", typeof(PT_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a --A IA listará scripts aqui.
        /// </summary>
        internal static string @__AI_will_output_scripts_here {
            get {
                return ResourceManager.GetString("--AI will output scripts here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Pesquisa profunda de scripts...).
        /// </summary>
        internal static string @__Deep_Searching_Scripts____ {
            get {
                return ResourceManager.GetString(" (Deep Searching Scripts...)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  (Pesquisando Scripts...).
        /// </summary>
        internal static string @__Searching_Scripts____ {
            get {
                return ResourceManager.GetString(" (Searching Scripts...)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (Carregando...).
        /// </summary>
        internal static string _loading____ {
            get {
                return ResourceManager.GetString("(loading...)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A IA está processando....
        /// </summary>
        internal static string AI_is_thinking___ {
            get {
                return ResourceManager.GetString("AI is thinking...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aimbot, ESP e mais funcionalidades na próxima atualização.
        /// </summary>
        internal static string Aimbot__ESP_e_mais_coisas_na_próxima_atualização {
            get {
                return ResourceManager.GetString("Aimbot, ESP e mais coisas na próxima atualização", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tudo Pronto!.
        /// </summary>
        internal static string All_Done_ {
            get {
                return ResourceManager.GetString("All Done!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bruh. Abrindo a janela de erro....
        /// </summary>
        internal static string Bruh__Opening_the_error_window___ {
            get {
                return ResourceManager.GetString("Bruh. Opening the error window...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altere as propriedades do seu personagem, use visuais e aimbots.
        /// </summary>
        internal static string Change_your_character_properties__use_visuals_and_aimbots {
            get {
                return ResourceManager.GetString("Change your character properties, use visuals and aimbots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altere o idioma do executor..
        /// </summary>
        internal static string Change_your_executor_language_ {
            get {
                return ResourceManager.GetString("Change your executor language.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificando login.
        /// </summary>
        internal static string Checking_Login {
            get {
                return ResourceManager.GetString("Checking Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificando status de manutenção.
        /// </summary>
        internal static string Checking_Maintence_status {
            get {
                return ResourceManager.GetString("Checking Maintence status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificando versão.
        /// </summary>
        internal static string Checking_Version {
            get {
                return ResourceManager.GetString("Checking Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha um dos idiomas disponíveis abaixo..
        /// </summary>
        internal static string Choose_one_of_the_available_languages_below_ {
            get {
                return ResourceManager.GetString("Choose one of the available languages below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar histórico.
        /// </summary>
        internal static string Clear_History {
            get {
                return ResourceManager.GetString("Clear History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escolha da Comunidade.
        /// </summary>
        internal static string Community_Choice {
            get {
                return ResourceManager.GetString("Community Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmar.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectando.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Continuar.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copiado.
        /// </summary>
        internal static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copiar Script.
        /// </summary>
        internal static string Copy_Script {
            get {
                return ResourceManager.GetString("Copy Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário atual: .
        /// </summary>
        internal static string Current_User__ {
            get {
                return ResourceManager.GetString("Current User: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Personalize sua conta.
        /// </summary>
        internal static string Customize_your_account {
            get {
                return ResourceManager.GetString("Customize your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Personalize sua experiência no Essence.
        /// </summary>
        internal static string Customize_your_Essence_experience {
            get {
                return ResourceManager.GetString("Customize your Essence experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir todos os registros de conversas com Mia.
        /// </summary>
        internal static string Delete_all_records_of_conversations_with_Mia {
            get {
                return ResourceManager.GetString("Delete all records of conversations with Mia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite o script aqui..
        /// </summary>
        internal static string Digite_o_script_aqui_ {
            get {
                return ResourceManager.GetString("Digite o script aqui.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RPC do Discord.
        /// </summary>
        internal static string Discord_RPC {
            get {
                return ResourceManager.GetString("Discord RPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha no download. Tente desativar seu software antivírus..
        /// </summary>
        internal static string Download_failed__try_to_disable_your_antivirus_software {
            get {
                return ResourceManager.GetString("Download failed. try to disable your antivirus software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ehh... Desculpe por isso.
        /// </summary>
        internal static string Ehh____Sorry_for_that {
            get {
                return ResourceManager.GetString("Ehh... Sorry for that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Personalização do Essence.
        /// </summary>
        internal static string Essence_Customization {
            get {
                return ResourceManager.GetString("Essence Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro de Alterações das Funcionalidades do Essence.
        /// </summary>
        internal static string Essence_Features_Changelog {
            get {
                return ResourceManager.GetString("Essence Features Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ative a atividade do Discord para o Essence. Uhul!.
        /// </summary>
        internal static string Enable_discord_activity_for_Essence__Yay_ {
            get {
                return ResourceManager.GetString("Enable discord activity for Essence. Yay!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Correspondências exatas para.
        /// </summary>
        internal static string Exact_Matches_for {
            get {
                return ResourceManager.GetString("Exact Matches for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Executar.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filtrando resultados com a IA....
        /// </summary>
        internal static string Filtering_results_with_AI___ {
            get {
                return ResourceManager.GetString("Filtering results with AI...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voar.
        /// </summary>
        internal static string Fly {
            get {
                return ResourceManager.GetString("Fly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Siga as regras para continuar usando nossos serviços..
        /// </summary>
        internal static string Follow_the_rules_to_continue_using_our_services_ {
            get {
                return ResourceManager.GetString("Follow the rules to continue using our services.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogo.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID do jogo: .
        /// </summary>
        internal static string Game_ID__ {
            get {
                return ResourceManager.GetString("Game ID: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID do jogo: Nenhum.
        /// </summary>
        internal static string Game_ID__None {
            get {
                return ResourceManager.GetString("Game ID: None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogos que você joga.
        /// </summary>
        internal static string Games_you_play {
            get {
                return ResourceManager.GetString("Games you play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obtendo nome do jogo....
        /// </summary>
        internal static string Getting_Game_Name___ {
            get {
                return ResourceManager.GetString("Getting Game Name...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obtendo informações do Roblox.
        /// </summary>
        internal static string Getting_Roblox_Info {
            get {
                return ResourceManager.GetString("Getting Roblox Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boa tarde.
        /// </summary>
        internal static string Good_Afternoon {
            get {
                return ResourceManager.GetString("Good Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boa noite.
        /// </summary>
        internal static string Good_Evening {
            get {
                return ResourceManager.GetString("Good Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bom dia.
        /// </summary>
        internal static string Good_Morning {
            get {
                return ResourceManager.GetString("Good Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boa madrugada.
        /// </summary>
        internal static string Good_Night {
            get {
                return ResourceManager.GetString("Good Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Olá.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Olá, Usuário.
        /// </summary>
        internal static string Hello_User {
            get {
                return ResourceManager.GetString("Hello User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Oi! Precisa de ajuda com scripts? Vamos começar!.
        /// </summary>
        internal static string Hi__Need_script_help__Let_s_begin_ {
            get {
                return ResourceManager.GetString("Hi! Need script help? Let\'s begin!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Página inicial.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horas.
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Eu consinto a coleta de dados do jogo para ajudar a melhorar o programa..
        /// </summary>
        internal static string I_consent_to_the_collection_of_game_data_to_help_improve_the_program_ {
            get {
                return ResourceManager.GetString("I consent to the collection of game data to help improve the program.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Insira um link de imagem aqui!.
        /// </summary>
        internal static string Insert_an_image_link_here_ {
            get {
                return ResourceManager.GetString("Insert an image link here!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intervalo.
        /// </summary>
        internal static string Intermission {
            get {
                return ResourceManager.GetString("Intermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Junte-se ao nosso evento musical para obter uma key gratuita!.
        /// </summary>
        internal static string Join_our_music_event_for_free_key_ {
            get {
                return ResourceManager.GetString("Join our music event for free key!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Manter o Essence acima de outras janelas.
        /// </summary>
        internal static string Keep_Essence_on_top_of_other_windows {
            get {
                return ResourceManager.GetString("Keep Essence on top of other windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resultados menos relevantes.
        /// </summary>
        internal static string Less_relevant_results {
            get {
                return ResourceManager.GetString("Less relevant results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vamos começar!.
        /// </summary>
        internal static string Lets_Start_ {
            get {
                return ResourceManager.GetString("Lets Start!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Key Linkvertise.
        /// </summary>
        internal static string Linkvertise_key {
            get {
                return ResourceManager.GetString("Linkvertise key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando conversas da IA.
        /// </summary>
        internal static string Loading_AI_Conversations {
            get {
                return ResourceManager.GetString("Loading AI Conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando registro de alterações (changelog)....
        /// </summary>
        internal static string Loading_Changelog___ {
            get {
                return ResourceManager.GetString("Loading Changelog...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando os Termos de Licença (EULA)....
        /// </summary>
        internal static string Loading_EULA___ {
            get {
                return ResourceManager.GetString("Loading EULA...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando próxima....
        /// </summary>
        internal static string Loading_Next___ {
            get {
                return ResourceManager.GetString("Loading Next...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando configurações.
        /// </summary>
        internal static string Loading_Settings {
            get {
                return ResourceManager.GetString("Loading Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando dados do usuário.
        /// </summary>
        internal static string Loading_User_Data {
            get {
                return ResourceManager.GetString("Loading User Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login Premium - Permanente.
        /// </summary>
        internal static string Login_Premium___Permanent {
            get {
                return ResourceManager.GetString("Login Premium - Permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enviando pedido....
        /// </summary>
        internal static string Making_Request___ {
            get {
                return ResourceManager.GetString("Making Request...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assistente Mia.
        /// </summary>
        internal static string Mia_Assistent {
            get {
                return ResourceManager.GetString("Mia Assistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Monaco é um editor avançado. No entanto, pode causar problemas de desempenho em alguns PCs..
        /// </summary>
        internal static string Monaco_is_an_advanced_editor__But__it_can_cause_performance_issues_in_some_pc_s {
            get {
                return ResourceManager.GetString("Monaco is an advanced editor. But, it can cause performance issues in some pc\'s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novos Scripts.
        /// </summary>
        internal static string New_Scripts {
            get {
                return ResourceManager.GetString("New Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Legal!.
        /// </summary>
        internal static string Nice_ {
            get {
                return ResourceManager.GetString("Nice!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Noclip.
        /// </summary>
        internal static string No_Clip {
            get {
                return ResourceManager.GetString("No Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados insuficientes. Jogue alguns jogos usando o Essence primeiro!.
        /// </summary>
        internal static string No_enough_data__play_some_games_using_Essence_first_ {
            get {
                return ResourceManager.GetString("No enough data. play some games using Essence first!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma conexão com a Internet detectada.
        /// </summary>
        internal static string No_Internet_Connection_Detected {
            get {
                return ResourceManager.GetString("No Internet Connection Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agora seu Essence está totalmente configurado.
        /// </summary>
        internal static string Now_Your_Essence_are_Fully_Configured {
            get {
                return ResourceManager.GetString("Now Your Essence are Fully Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abrir.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nossa IA está pronta para ajudá-lo!.
        /// </summary>
        internal static string Our_AI_is_ready_to_help_you_ {
            get {
                return ResourceManager.GetString("Our AI is ready to help you!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nossos servidores estão sendo atualizados!.
        /// </summary>
        internal static string Our_servers_are_updating_ {
            get {
                return ResourceManager.GetString("Our servers are updating!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID do jogador: .
        /// </summary>
        internal static string Player_ID__ {
            get {
                return ResourceManager.GetString("Player ID: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogadores online: .
        /// </summary>
        internal static string Players_online__ {
            get {
                return ResourceManager.GetString("Players online: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogadores online: Carregando....
        /// </summary>
        internal static string Players_online__Loading___ {
            get {
                return ResourceManager.GetString("Players online: Loading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogando .
        /// </summary>
        internal static string Playing_ {
            get {
                return ResourceManager.GetString("Playing ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Playlist vazia..
        /// </summary>
        internal static string Playlist_Empty_ {
            get {
                return ResourceManager.GetString("Playlist Empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, verifique as configurações de rede e firewall para restaurar o acesso..
        /// </summary>
        internal static string Please_check_your_network_settings_and_firewall_configuration_to_restore_access_ {
            get {
                return ResourceManager.GetString("Please check your network settings and firewall configuration to restore access.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login Premium (ADM).
        /// </summary>
        internal static string Premium_Login__ADM_ {
            get {
                return ResourceManager.GetString("Premium Login (ADM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preparando primeira execução...
        /// </summary>
        internal static string Preparing_First_Run__ {
            get {
                return ResourceManager.GetString("Preparing First Run..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preparando primeira execução....
        /// </summary>
        internal static string Preparing_First_Run___ {
            get {
                return ResourceManager.GetString("Preparing First Run...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foto de Perfil.
        /// </summary>
        internal static string Profile_Picture {
            get {
                return ResourceManager.GetString("Profile Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações do Perfil.
        /// </summary>
        internal static string Profile_Settings {
            get {
                return ResourceManager.GetString("Profile Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Painel Rápido.
        /// </summary>
        internal static string Quick_Panel {
            get {
                return ResourceManager.GetString("Quick Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coisas rápidas que você pode alterar.
        /// </summary>
        internal static string Quick_things_you_can_change {
            get {
                return ResourceManager.GetString("Quick things you can change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualizar.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resultados para.
        /// </summary>
        internal static string Results_for {
            get {
                return ResourceManager.GetString("Results for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar conversas.
        /// </summary>
        internal static string Save_conversations {
            get {
                return ResourceManager.GetString("Save conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salve suas guias de script para recarregá-las quando abrir o Essence novamente.
        /// </summary>
        internal static string Save_your_script_tabs_to_re_load_then_when_you_open_Essence_again {
            get {
                return ResourceManager.GetString("Save your script tabs to re-load then when you open Essence again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scripts Salvos.
        /// </summary>
        internal static string Saved_Scripts {
            get {
                return ResourceManager.GetString("Saved Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hub de Scripts.
        /// </summary>
        internal static string Script_Cloud {
            get {
                return ResourceManager.GetString("Script Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scripts para versões anteriores deste jogo: .
        /// </summary>
        internal static string Scripts_for_past_versions_of_this_game__ {
            get {
                return ResourceManager.GetString("Scripts for past versions of this game: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scripts para este jogo: .
        /// </summary>
        internal static string Scripts_for_this_game__ {
            get {
                return ResourceManager.GetString("Scripts for this game: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scripts para este jogo: Carregando....
        /// </summary>
        internal static string Scripts_for_this_game__Loading___ {
            get {
                return ResourceManager.GetString("Scripts for this game: Loading...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scripts para esta versão do jogo: .
        /// </summary>
        internal static string Scripts_for_this_game_version__ {
            get {
                return ResourceManager.GetString("Scripts for this game version: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar scripts.
        /// </summary>
        internal static string Search_scripts {
            get {
                return ResourceManager.GetString("Search scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisando....
        /// </summary>
        internal static string Searching___ {
            get {
                return ResourceManager.GetString("Searching...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mudar de Servidor.
        /// </summary>
        internal static string Server_Hop {
            get {
                return ResourceManager.GetString("Server Hop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definir Poder de Salto .
        /// </summary>
        internal static string Set_JumpPower_ {
            get {
                return ResourceManager.GetString("Set JumpPower ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definir Velocidade de Caminhada .
        /// </summary>
        internal static string Set_WalkSpeed_ {
            get {
                return ResourceManager.GetString("Set WalkSpeed ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pular.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pulando música....
        /// </summary>
        internal static string Skipping_music___ {
            get {
                return ResourceManager.GetString("Skipping music...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desculpe, seu idioma não é suportado.
        /// </summary>
        internal static string Sorry__your_language_is_not_supported {
            get {
                return ResourceManager.GetString("Sorry, your language is not supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciando Interface de Usuário....
        /// </summary>
        internal static string Starting_UI___ {
            get {
                return ResourceManager.GetString("Starting UI...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sugerido por: .
        /// </summary>
        internal static string Suggested_by__ {
            get {
                return ResourceManager.GetString("Suggested by: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Jogos sugeridos.
        /// </summary>
        internal static string Suggested_games {
            get {
                return ResourceManager.GetString("Suggested games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sincronizado com seu Discord.
        /// </summary>
        internal static string Synced_with_your_discord {
            get {
                return ResourceManager.GetString("Synced with your discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Converse com o assistente aqui.
        /// </summary>
        internal static string Talk_to_assistent_here {
            get {
                return ResourceManager.GetString("Talk to assistent here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Isso está levando mais tempo do que o esperado....
        /// </summary>
        internal static string This_is_taking_longer_than_expected___ {
            get {
                return ResourceManager.GetString("This is taking longer than expected...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Essa opção salva e carrega todo o histórico de conversas com Mia..
        /// </summary>
        internal static string This_option_saves_and_loads_all_your_chat_history_with_Mia_ {
            get {
                return ResourceManager.GetString("This option saves and loads all your chat history with Mia.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Manter a janela no topo.
        /// </summary>
        internal static string Top_Most_the_window {
            get {
                return ResourceManager.GetString("Top-Most the window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ação não autorizada detectada. Pare imediatamente para evitar medidas adicionais..
        /// </summary>
        internal static string Unauthorized_action_detected__Stop_immediately_to_avoid_further_measures_ {
            get {
                return ResourceManager.GetString("Unauthorized action detected. Stop immediately to avoid further measures.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome de Usuário.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a usuários ouvindo: .
        /// </summary>
        internal static string users_listening__ {
            get {
                return ResourceManager.GetString("users listening: ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifique para acessar nossos serviços.
        /// </summary>
        internal static string Verify_to_access_our_services {
            get {
                return ResourceManager.GetString("Verify to access our services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificar usando Discord.
        /// </summary>
        internal static string Verify_using_Discord {
            get {
                return ResourceManager.GetString("Verify using Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguardando o usuário entrar em um jogo..
        /// </summary>
        internal static string Waiting_for_user_to_join_a_game_ {
            get {
                return ResourceManager.GetString("Waiting for user to join a game.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estamos atualizando nossos serviços. Por favor, tente novamente mais tarde..
        /// </summary>
        internal static string We_re_updating_our_services__Please_try_again_later_ {
            get {
                return ResourceManager.GetString("We\'re updating our services. Please try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo, estamos felizes em tê-lo conosco!.
        /// </summary>
        internal static string Welcome__we_are_grateful_to_have_you_with_us_ {
            get {
                return ResourceManager.GetString("Welcome, we are grateful to have you with us!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo, usuário!.
        /// </summary>
        internal static string Welcome_User_ {
            get {
                return ResourceManager.GetString("Welcome User!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novidades.
        /// </summary>
        internal static string What_s_New {
            get {
                return ResourceManager.GetString("What\'s New", resourceCulture);
            }
        }
    }
}
